version: '3.8'

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.docker.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
  api:
    build: .
    env_file: ./.docker.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    depends_on:
      - mongodb
      - redis
    redis:
      image: redis:6.2-alpine
      env_file: ./.docker.env
      restart: unless-stopped
      ports:
        - $REDIS_LOCAL_PORT:$REDIS_DOCKER_PORT
      command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
      volumes:
        - redis:/data

volumes:
  db:
  redis:
    driver: local
